# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(510, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_email = QtWidgets.QLabel(Dialog)
        self.label_email.setObjectName("label_email")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_email)
        self.line_email = QtWidgets.QLineEdit(Dialog)
        self.line_email.setObjectName("line_email")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_email)
        self.label_password = QtWidgets.QLabel(Dialog)
        self.label_password.setObjectName("label_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_password)
        self.line_password = QtWidgets.QLineEdit(Dialog)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setObjectName("line_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_password)
        self.horizontalLayout_4.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.button_login = QtWidgets.QPushButton(Dialog)
        self.button_login.setObjectName("button_login")
        self.horizontalLayout_4.addWidget(self.button_login)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_signup = QtWidgets.QLabel(Dialog)
        self.label_signup.setTextFormat(QtCore.Qt.PlainText)
        self.label_signup.setAlignment(QtCore.Qt.AlignCenter)
        self.label_signup.setObjectName("label_signup")
        self.horizontalLayout_2.addWidget(self.label_signup)
        self.button_signup = QtWidgets.QPushButton(Dialog)
        self.button_signup.setObjectName("button_signup")
        self.horizontalLayout_2.addWidget(self.button_signup)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_email.setText(_translate("Dialog", "Email:"))
        self.label_password.setText(_translate("Dialog", "Password:"))
        self.button_login.setText(_translate("Dialog", "Login"))
        self.label_signup.setText(_translate("Dialog", "Don\'t have account?"))
        self.button_signup.setText(_translate("Dialog", "Sign up"))
