# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(789, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setObjectName("grid_layout")
        self.activity_tracker_button = QtWidgets.QPushButton(self.centralwidget)
        self.activity_tracker_button.setObjectName("activity_tracker_button")
        self.grid_layout.addWidget(self.activity_tracker_button, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grid_layout.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.grid_layout.addItem(spacerItem2, 0, 0, 1, 1)
        self.sign_language_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_language_button.setObjectName("sign_language_button")
        self.grid_layout.addWidget(self.sign_language_button, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.grid_layout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.graph_view = QtWidgets.QVBoxLayout()
        self.graph_view.setObjectName("graph_view")
        self.horizontalLayout_2.addLayout(self.graph_view)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menubar.setAcceptDrops(True)
        self.menubar.setAutoFillBackground(True)
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setAutoFillBackground(False)
        self.menu_help.setSeparatorsCollapsible(False)
        self.menu_help.setToolTipsVisible(False)
        self.menu_help.setObjectName("menu_help")
        self.menu_account = QtWidgets.QMenu(self.menubar)
        self.menu_account.setObjectName("menu_account")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_signedin = QtWidgets.QAction(MainWindow)
        self.action_signedin.setCheckable(False)
        self.action_signedin.setEnabled(False)
        self.action_signedin.setText("")
        self.action_signedin.setMenuRole(QtWidgets.QAction.NoRole)
        self.action_signedin.setObjectName("action_signedin")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_signout = QtWidgets.QAction(MainWindow)
        self.action_signout.setObjectName("action_signout")
        self.menu_help.addAction(self.action_about)
        self.menu_account.addAction(self.action_signedin)
        self.menubar.addAction(self.menu_account.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.activity_tracker_button.setText(_translate("MainWindow", "Start Activity Tracker"))
        self.sign_language_button.setText(_translate("MainWindow", "Start Sign Language"))
        self.menu_help.setTitle(_translate("MainWindow", "Help"))
        self.menu_account.setTitle(_translate("MainWindow", "Account"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.action_about.setText(_translate("MainWindow", "About"))
        self.action_signout.setText(_translate("MainWindow", "Sign out"))
