# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(556, 454)
        MainWindow.setMinimumSize(QtCore.QSize(556, 454))
        MainWindow.setMaximumSize(QtCore.QSize(556, 454))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_label = QtWidgets.QLabel(self.centralwidget)
        self.input_label.setGeometry(QtCore.QRect(150, 20, 131, 16))
        self.input_label.setObjectName("input_label")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(270, 90, 75, 23))
        self.ok_button.setObjectName("ok_button")
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.delete_button.setObjectName("delete_button")
        self.info_button = QtWidgets.QPushButton(self.centralwidget)
        self.info_button.setGeometry(QtCore.QRect(360, 52, 41, 21))
        self.info_button.setObjectName("info_button")
        self.line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit.setGeometry(QtCore.QRect(150, 50, 201, 21))
        self.line_edit.setObjectName("line_edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.delete_button, self.ok_button)
        MainWindow.setTabOrder(self.ok_button, self.info_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_label.setText(_translate("MainWindow", "Masukkan fungsi transfer:"))
        self.ok_button.setText(_translate("MainWindow", "OK"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.info_button.setText(_translate("MainWindow", "Help"))
        self.action_New.setText(_translate("MainWindow", "&New"))
