# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(556, 454)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.prompt_label = QtWidgets.QLabel(self.centralwidget)
        self.prompt_label.setGeometry(QtCore.QRect(40, 20, 131, 16))
        self.prompt_label.setObjectName("prompt_label")
        self.ok_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(270, 120, 75, 23))
        self.ok_button.setObjectName("ok_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(160, 120, 75, 23))
        self.clear_button.setObjectName("clear_button")
        self.info_button = QtWidgets.QPushButton(self.centralwidget)
        self.info_button.setGeometry(QtCore.QRect(470, 70, 41, 21))
        self.info_button.setObjectName("info_button")
        self.num_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.num_edit.setGeometry(QtCore.QRect(40, 70, 201, 21))
        self.num_edit.setObjectName("num_edit")
        self.den_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.den_edit.setGeometry(QtCore.QRect(260, 70, 201, 21))
        self.den_edit.setObjectName("den_edit")
        self.num_label = QtWidgets.QLabel(self.centralwidget)
        self.num_label.setGeometry(QtCore.QRect(40, 50, 131, 16))
        self.num_label.setObjectName("num_label")
        self.den_label = QtWidgets.QLabel(self.centralwidget)
        self.den_label.setGeometry(QtCore.QRect(260, 50, 131, 16))
        self.den_label.setObjectName("den_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.action_New = QtWidgets.QAction(MainWindow)
        self.action_New.setObjectName("action_New")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.clear_button, self.ok_button)
        MainWindow.setTabOrder(self.ok_button, self.info_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.prompt_label.setText(_translate("MainWindow", "Masukkan fungsi transfer:"))
        self.ok_button.setText(_translate("MainWindow", "OK"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        self.info_button.setText(_translate("MainWindow", "Help"))
        self.num_label.setText(_translate("MainWindow", "Pembilang:"))
        self.den_label.setText(_translate("MainWindow", "Penyebut:"))
        self.action_New.setText(_translate("MainWindow", "&New"))
